### ISSUE TITLE
Tag list arrow jumps to the right side sometimes

### ISSUE THREAD

**Issue by Tallivm** [GeekCafeAI/SmartNotes#30]
To reproduce, just select some tags. If ticks are still appearing, the the list shifts and sometimes the arrow jumps to the right side. See the screenshot.
![image](https://user-images.githubusercontent.com/30693065/211415007-5c140f89-60eb-4470-b76c-0158886a1692.png)

**Comment by MFisenko** [comment]
Issue fixed arrow now always under tags when expanded
