### ISSUE TITLE
Prompt Engineering

### ISSUE THREAD

**Issue by Misterion777** [GeekCafeAI/SmartNotes#5]
## Principles
1. Prompt should contain few-shot examples.
2. Prompt should be as concise as possible.
3. Prompt can be split into parts (multiple requests).
4. Dates can be parsed without GPT, using [dateparser](https://dateparser.readthedocs.io/en/latest/index.html)
5. Synonyms can be found without GPT, using [nltk.wordnet](https://www.nltk.org/howto/wordnet.html)

### Find categories
> Extract up to three categories from the text. A text that reminds of any event should have reminder category.
[text]: Meeting is tomorrow at 10 am.
[categories]: reminder, meeting, work
[text]: buy sour cream, potatoes, eggs, flour to make some potato pancakes
[categories]: shopping, cooking
[text]: take a pill 3 times a day
[categories]: <reminder, medication, health>
### Find dates (should be applied only to those texts that contain "reminder" category)
> Extract a date from text:
[text]: Meeting is tomorrow at 10 am.
[date]: tomorrow at 10 am
[text]: buy products required for caesar salad by monday. guests are coming at 7pm
[date]: <monday at 7 pm>
### Custom categories mapping 
We can have a dictionary for each user that maps GPT categories to custom and change them on output.

## Parameters
* temperature = 0: deterministic behaviour
* top_p = 0: same as above, deterministic behaviour
* logprobs = 5: returns candidate tokens for each token. can be filtered afterwards according to custom user categories
* presence_penalty can be set to negative value (-0.1 to -1) to increase determinism even more

**Comment by Tallivm** [comment]
MVP is done.
